### ISSUE TITLE
dotnet restore throws error: The imported project "***Microsoft.DNX.Props" was not found

### ISSUE THREAD

**Issue by tautonic** [IBM-Cloud/aspnet-core-helloworld#29]
Followed the steps, able to run Hello World console and web dotnet core apps. Then:

  187  git clone https://github.com/IBM-Bluemix/aspnet-core-helloworld.git
  188  cd aspnet-core-helloworld/src/WebApplication/
  189  dotnet restore

/Users/****/dev/pcf/aspnet-core-helloworld/src/WebApplication/WebApplication.xproj(7,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/1.0.1/Microsoft/VisualStudio/v14.0/DNX/Microsoft.DNX.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by itzunagi** [comment]
@tautonic Which .NET SDK version are you using? (run `dotnet --version` from the project folder)  From the error message it looks like you might be running the latest SDK which only supports MSBuild projects (this repository's main branch is currently a project.json project), if that is the case try checking out the develop branch (`git checkout develop`) first.

**Comment by tautonic** [comment]
dotnet --version
1.0.1

Im new to dotnet core but it doesn't seem like this is the latest version. 

Then when I run dotnet, I get this:
dotnet

Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86


Weird but develop branch worked so I this is not an issue with this project, rather version of dotnet.
Thanks!

**Comment by itzunagi** [comment]
@tautonic The result of `dotnet --version` is the SDK version number, the "Version: 1.1.0" in the output of `dotnet` is the Framework version number.  The latest SDK version is version 1.0.1.
